# Generated by Django 3.2.6 on 2021-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alpha2Code', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
                ('flag', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alpha3Code', models.CharField(max_length=10)),
                ('countries', models.ManyToManyField(related_name='neighbours', to='countries.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('countries', models.ManyToManyField(related_name='languages', to='countries.Country')),
            ],
        ),
    ]
